const actionTypes = {
    SET_VIEW_MODE: 'SET_VIEW_MODE',
    SET_SELECTED_IMAGES: 'SET_SELECTED_IMAGES',
    SET_DOWNLOADED_IDS: 'SET_DOWNLOADED_IDS',
    UPDATE_IMAGES_LIST: 'UPDATE_IMAGES_LIST'
}

export default actionTypes
